### PR TITLE
 homepage

### LINKED ISSUE #1: Design Homepage
**Task title**
Design Homepage

**Task description**
Design responsive homepage, (ar, en) layouts

**Subtasks**

1. Hero section.
2. How It Works.
3. Sustainable Development Goals.
4. Hear it from volunteers.
5. Gallery.
6. Last Section.

**Screenshots**

Large Screen
indexPage

Tablet Screen
indexPage(tablet wireframe)

Mobile Screen
indexPage(mobile wireframe)

**Link to the component on Figma**
[Home Page](https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1830-6671&t=gl9EKVkeewmOfhRc-4)

### PR DESCRIPTION
**Pull request by RuqaiahSaif**
add home page components
 
##Screenshot page
screencapture-localhost-3000-ar-2023-04-01-04_04_53
localhost_3000_ar(iPhone SE)

### CODE REVIEW

**Review by fatGubari — APPROVED** [review]
keep your good work

**Review by fatGubari — APPROVED** [review]
Great job but don't forget to add the screenshot images

**Comment by RuqaiahSaif** [comment]
> Great job but don't forget to add the screenshot images

ok I do it ^-^

**Review by ramizapk — APPROVED** [review]
Great job

**Pull request merged**
