### PR TITLE
 design event creation page

### LINKED ISSUE #16: Design Event Creation Page
**Task title**
Design Event Creation Page

**Task description**
Design responsive Event Creation Page, (ar, en) layouts

**Screenshots**
Large Screen
d

Tablet Screen
t

Mobile Screen
m

**Link to the component on Figma**
[Event Creation Page](https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1663-2805&t=3Nv4MEPPPOngaDTX-4)

### PR DESCRIPTION
**Pull request by RuqaiahSaif**
design event creation page
screencapture-localhost-3000-eventcreation-2023-04-03-22_54_44

### CODE REVIEW

**Review by fatGubari — APPROVED** [review]
I love how you finish your work on time

**Review by ramizapk — COMMENTED** [review]
the event type checkbox desgin is not responsive with different screens Please modify it

**Review by fatGubari — COMMENTED** [review]
add some padding to inputs

**Comment by RuqaiahSaif** [comment]
> the event type checkbox desgin is not responsive with different screens Please modify it

thanks, ok I will modify it

**Comment by RuqaiahSaif** [comment]
> add some padding to inputs
ok

**Review by Hekmat33-MO — APPROVED** [review]

**Pull request merged**
